name: 'Deploy Registrations'

on:
  push:
    branches: ['main']

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build Distribution
        run: npx github:hubmapconsortium/hra-rui-locations-processor deploy-dir digital-objects dist

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: gh-pages
          commit_message: "Deploy -- ${{ github.event.head_commit.message }}"
